version: '3'

services:
  postgres:
    image: 'postgres:15.1-alpine'
    container_name: 'database'
    environment:
      - 'POSTGRES_DB=azura'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=root'
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"

  app:
    image: lesn0y/azura-backend:0.0.1
    container_name: 'backend'
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  db-data:
